---
- hosts: all
  become: yes
  become_user: root

  tasks:

  - name: Delete old files
    shell: "rm -f /var/ansible-dir/enamysl/docker_test/images_scan/*"
    run_once: true
    delegate_to: localhost

  - name: Delete old file for Python
    shell: "echo '' > /var/ansible-dir/enamysl/docker_test/inactive_containers.txt"
    run_once: true
    delegate_to: localhost

  - name: Looking for inactive containers
    shell: "docker system df -v | grep -v mirantis | sed -n '/^REPOSITORY\|^abc\|^xyz\|^qwerty/p' | (sed -u 1q; sort -k1,1 -k2r) | (sed -u 1q; sed -n '/0$/p')"
    register: my_output
    ignore_errors: yes

  - name: Write to file
    lineinfile:
      dest: /var/ansible-dir/enamysl/docker_test/images_scan/{{ansible_hostname}}.txt
      line: "{{ ansible_hostname }} \n {{ my_output.stdout }} \n\n"
      create: yes
    when: my_output.stdout != ""
    delegate_to: localhost

  - name: Run Python script to clean the output and concatenate it to one file
    shell: "python3 /var/ansible-dir/enamysl/docker_test/iterate_files_new.py"
    run_once: true
    ignore_errors: yes
    delegate_to: localhost

  - name: Send email
    become: false
    mail:
      attach: /var/ansible-dir/enamysl/docker_test/inactive_containers.txt
      to: enamysl@somedomain.com
      subject: 'Status of inactive containers {{ansible_date_time.date}}'
      body: 'Status of inactive containers in the attached file :)'
      host: exchange.xyz.somedomain.com
      from: "docker_containers_notification@somedomain.com"
      secure: never
    run_once: true
    delegate_to: localhost 
